language: node_js

env:
  - WEBPACK_VERSION="latest"
  - WEBPACK_VERSION="4.39.3"
node_js:
  - "lts/*"
  - "10"
  - "8"

before_install:
  - nvm --version
  - node --version
install: "yarn install --frozen-lockfile --ignore-engines"
before_script:
  - yarn add webpack@$WEBPACK_VERSION --ignore-engines
script:
  - yarn run test

jobs:
  include:
    - stage: release
      node_js: "lts/*"
      deploy:
        provider: script
        script: "yarn semantic-release"
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(master|next)$
