name: "Build & Test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, lts/*]
        webpack: [5.58.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile --ignore-engines
      - run: yarn add webpack@${{ matrix.webpack }} --ignore-engines
      - run: yarn run test
